services:
  MiVOLO:
    container_name: MiVOLO
    tty: true
    image: python:3.12-slim
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: ['gpu']